title: Hongyi Zhu's Homepage
page-top-title: Hongyi Zhu
top-section-bg-text: Architecture & Urban Planning
home-subtitle: Hongyi Zhu|朱弘毅
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
